# https://taskfile.dev

version: "3"

# env:
#   NEO4J_URI: "bolt://localhost:7687"
#   # NEO4J_USERNAME: "neo4j"
#   # NEO4J_PASSWORD: "password"
#   NEO4J_DATABASE: "neo4j"
#   NEO4J_MCP_TRANSPORT: "http"
#   NEO4J_MCP_HTTP_PORT: "8080"

tasks:
  build:
    cmds:
      - go build -C cmd/flow-microstrategy-mcp -o ../../bin/ {{.CLI_ARGS}}
  run:
    cmds:
      - go run ./cmd/flow-microstrategy-mcp
  run:compiled:
    cmds:
      - ./bin/flow-microstrategy-mcp {{.CLI_ARGS}}
  generate:
    cmds:
      - go generate ./...
  # pass CLI args as task:test -- -v
  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}
  test:unit:
    cmds:
      - go test ./internal/... {{.CLI_ARGS}}
  test:int:
    cmds:
      - go test -tags=integration ./test/integration/... {{.CLI_ARGS}}
  test:e2e:
    cmds:
      - go test -tags=e2e ./test/e2e/... {{.CLI_ARGS}}
  test:clean:
    cmds:
      - go clean -testcache
  lint:
    cmds:
      - golangci-lint run
  inspect:
    cmds:
      - npx @modelcontextprotocol/inspector go run ./cmd/flow-microstrategy-mcp
  interactive-client:
    cmds:
      - go run ./client/... bin/flow-microstrategy-mcp
